name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Prepare Build Settings
      working-directory: ./Android
      run: |
        echo "${{ secrets.KEYSTORE }}" | base64 -d > iph.keystore
        ls -al
        url=${{ secrets.INDEX_URL }}
        url=${url//\//\\\/}
        sed -i "s/url\">.*</url\">$url</g" app/src/main/res/values/strings.xml
        cat app/src/main/res/values/strings.xml
        echo -e "\nRELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> gradle.properties
        echo "RELEASE_KEY_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> gradle.properties
        cat gradle.properties

    - name: Gradle Build
      working-directory: ./Android
      run: ./gradlew assembleRelease
